# This file was generated by GoReleaser. DO NOT EDIT.
cask "heimdall" do
  version "0.3.4"

  on_macos do
    on_intel do
      sha256 "b696a621b222873799c2f59a019aa490dc5fd9f98765f9ae34c49d9d396e3d9e"
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bc2c255ccdec6c832f1cb1de4c2cc8a1dbbf04fa330ee9e4a30506907d4e9cb"
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3b0de04505c33d0c9641466362de247726fdc5bcad35091ad4a85638085156a8"
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "022e9dd6aa80f67d837922650464451656c4f31946d6de5db49c8c97533df5a0"
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_linux_arm64.tar.gz"
    end
  end

  name "heimdall"
  desc "Heimdall CLI — query observability data from your terminal or AI agent"
  homepage "https://heimdall.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heimdall"

  # No zap stanza required

end
