# This file was generated by GoReleaser. DO NOT EDIT.
cask "heimdall" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_darwin_amd64.tar.gz"
      sha256 "b857a2538345fc2d36b76fdee61326c5756de81fdc7779bd3908a31dfdc36b89"
    end
    on_arm do
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_darwin_arm64.tar.gz"
      sha256 "8e28c7cadbfccdaa67f9ef038f132bed8e2b50284c28a81c5dd2375264a41922"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_linux_amd64.tar.gz"
      sha256 "914bd30427e63defd2054fafe538a21b64a766db6f681985b7249b6730658aaa"
    end
    on_arm do
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_linux_arm64.tar.gz"
      sha256 "3f0f3e893f7d4b506d3d03da8d99a11eddcf99432a2a4b65ab2cac55d6f74f31"
    end
  end

  name "heimdall"
  desc "Heimdall CLI — query observability data from your terminal or AI agent"
  homepage "https://heimdall.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heimdall"

  # No zap stanza required

end
