# This file was generated by GoReleaser. DO NOT EDIT.
cask "heimdall" do
  version "0.3.6"

  on_macos do
    on_intel do
      sha256 "a38f56510caecc469a1895d841e6b99b95319e52b98e768ea1eb724d082b8687"
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f88d44431e3faea01d36f163ad85560b793f038782e34a33601c581b448e54a"
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc906043f0c6c682d7d8e9d876ad604717099c7d52e83d42e8272acda3fe281e"
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a716931e584a8d888c50e2c0499c716b8d6d0573cb06f10d6ef8621b306289e"
      url "https://github.com/octbte/heimdall-cli/releases/download/v#{version}/heimdall_linux_arm64.tar.gz"
    end
  end

  name "heimdall"
  desc "Heimdall CLI — query observability data from your terminal or AI agent"
  homepage "https://heimdall.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heimdall"

  # No zap stanza required

end
